export const MESSAGE_TYPES = {
  OPEN_EXTERNAL_BROWSER: 'OPEN_EXTERNAL_BROWSER',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  REQUEST_NOTIFICATION_PERMISSION: 'REQUEST_NOTIFICATION_PERMISSION',
  LOGOUT: 'LOGOUT',
} as const;

export type MessageType = (typeof MESSAGE_TYPES)[keyof typeof MESSAGE_TYPES];
