export const MESSAGE_TYPES = {
  OPEN_EXTERNAL_BROWSER: 'OPEN_EXTERNAL_BROWSER',
  OAUTH_LOGIN_EXTERNAL: 'OAUTH_LOGIN_EXTERNAL',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  TOKEN: 'TOKEN',
  NEED_REGISTER: 'NEED_REGISTER',
} as const;

export type MessageType = (typeof MESSAGE_TYPES)[keyof typeof MESSAGE_TYPES];
