import { NotificationResponse } from './api';

export const mockNotifications: NotificationResponse[] = [
  {
    id: 1,
    stockId: 904,
    stockName: '삼성전자',
    notificationType: 'SCORE_SPIKE',
    oldScore: 85,
    newScore: 86,
    changeAbs: 1,
    title: '인간지표 변동 알림',
    body: '인간지표가 1점 올랐어요',
    isRead: false,
    createdAt: '2025-01-01',
    country: 'KOREA',
  },
  {
    id: 2,
    stockId: 89,
    stockName: 'NAVER',
    notificationType: 'SCORE_SPIKE',
    oldScore: 51,
    newScore: 50,
    changeAbs: 1,
    title: '인간지표 변동 알림',
    body: '인간지표가 1점 내렸어요',
    isRead: false,
    createdAt: '2025-01-01',
    country: 'KOREA',
  },
  {
    id: 3,
    stockId: 5990,
    stockName: '인텔',
    notificationType: 'SCORE_SPIKE',
    oldScore: 43,
    newScore: 44,
    changeAbs: 1,
    title: '인간지표 변동 알림',
    body: '인간지표가 1점 올랐어요',
    isRead: false,
    createdAt: '2025-01-01',
    country: 'OVERSEA',
  },
  {
    id: 4,
    stockId: 2716,
    stockName: '한화',
    notificationType: 'SCORE_SPIKE',
    oldScore: 89,
    newScore: 90,
    changeAbs: 1,
    title: '인간지표 변동 알림',
    body: '인간지표가 1점 올랐어요',
    isRead: false,
    createdAt: '2025-01-01',
    country: 'KOREA',
  },
];
