# .github/workflows/main.yml
name: helloGithubAction
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: print "hello world"
        run : echo Hello, World!
      - name: print directory structure
        run : ls -al
#Github Actions 안씁니다.